version = 1
SPDX-PackageName = "Visual XSharp Website"
SPDX-PackageSupplier = "Organization: Progmasoft"
SPDX-PackageDownloadLocation = "https://github.com/Progmasoft/website"

[[annotations]]
path = ["backend/appsettings.json", "dotnet-tools.json", "frontend/package-lock.json", "frontend/package.json", "frontend/public/xsharp-logo.webp", "frontend/tsconfig.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Progmasoft <support@progmasoft.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later WITH AdditionRef-Progmasoft-Patent-Grant-1.0"
