# SPDX-FileCopyrightText: 2026 Progmasoft <support@progmasoft.com>
# SPDX-License-Identifier: AGPL-3.0-or-later WITH AdditionRef-Progmasoft-Patent-Grant-1.0

protocols = imap
listen = *, ::
mail_location = maildir:~/Maildir
mail_privileged_group = mail
first_valid_uid = 1000

disable_plaintext_auth = yes
auth_mechanisms = plain login
auth_username_format = %Ln

ssl = required
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
ssl_cert = </etc/letsencrypt/live/mail.progmasoft.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.progmasoft.com/privkey.pem

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}
