# SPDX-FileCopyrightText: 2026 Progmasoft <support@progmasoft.com>
# SPDX-License-Identifier: AGPL-3.0-or-later WITH AdditionRef-Progmasoft-Patent-Grant-1.0

Syslog yes
SyslogSuccess yes
LogWhy yes
Canonicalization relaxed/simple
Mode s
SubDomains no
OversignHeaders From
Domain progmasoft.com
Selector registry
KeyFile /etc/opendkim/keys/progmasoft.com/registry.private
Socket inet:8891@127.0.0.1
PidFile /run/opendkim/opendkim.pid
UMask 007
UserID opendkim:opendkim
RequireSafeKeys yes
