# SPDX-FileCopyrightText: 2026 Leitwolf <xs-lang.chess031@slmails.com>
# SPDX-License-Identifier: Apache-2.0

Syslog yes
SyslogSuccess yes
LogWhy yes
Canonicalization relaxed/simple
Mode s
SubDomains no
OversignHeaders From
Domain xsharp-lang.xyz
Selector registry
KeyFile /etc/opendkim/keys/xsharp-lang.xyz/registry.private
Socket inet:8891@127.0.0.1
PidFile /run/opendkim/opendkim.pid
UMask 007
UserID opendkim:opendkim
RequireSafeKeys yes
